### ISSUE TITLE
为什么扫描的蓝牙设备名称基本都显示是未命名的设备呢？

### ISSUE THREAD

**Issue by Villian95** [pineappleoOilPrince/flutter_blue_elves#29]

**Comment by ggokbudak** [comment]
FlutterBlueElves.instance
                      .startScan(500000, isAllowDuplicates: true)
                      .listen((event) {
                    setState(() {
                      final existingDeviceIndex =
                          _persistentScanList.lastIndexWhere(
                        //LAST INDEXİ ALACAK ŞEKİLDE GÜNCELLENDİ
                        (element) => element.macAddress == event.macAddress,
                      );

                      if (existingDeviceIndex != -1) {
                        // Eğer cihaz listede varsa, güncel zamanı kaydet
                        _persistentScanList[existingDeviceIndex] = event;
                      } else {
                        // Eğer cihaz listede yoksa, yeni cihaz olarak ekle
                        _persistentScanList.add(event);
                      }

                      if (event.macAddress != null && ///YOU CAN CHECK THİS!!!!
                          event.name != null &&
                          int.tryParse(event.name!) != null) {
                        _scanResultList.insert(0, event);
                      }
                      ParseDataForNode();
                      //logScanResults();
                      //sad();
                    });
                  }).onDone(() {
                    setState(() {
                      _isScaning = false;
                      _persistentScanList.clear();
                    });
                  });
                }
              }
            },
