### ISSUE TITLE
Scan can't find the device

### ISSUE THREAD

**Issue by yh4922** [pineappleoOilPrince/flutter_blue_elves#5]
After checking the Bluetooth open state, call the `flutterblueelves.instance.startscan (5000)` scanning device, but there is no result, the terminal outputs the log
```
I/flutter (27789): ble status：true,  start scaning
D/BluetoothAdapter(27789): isLeEnabled(): ON
D/BluetoothLeScanner(27789): could not find callback wrapper
D/BluetoothAdapter(27789): isLeEnabled(): ON
D/BluetoothLeScanner(27789): onScannerRegistered() - status=0 scannerId=7 mScannerId=0
2
D/BluetoothAdapter(27789): isLeEnabled(): ON
D/BluetoothLeScanner(27789): could not find callback wrapper
```

I don't know what the reason is caused, permissions or configuration files❓

**Comment by pineappleoOilPrince** [comment]
Did you call listen() after startscan?
Such as: FlutterBlueElves.instance.startScan(5000).listen((event){})

**Comment by yh4922** [comment]
我是这样调用的
```
/// 扫描BLE设备
static void scanBle (void Function(ScanResult) onData) {
  FlutterBlueElves.instance.startScan(5000).listen(onData);
}
```

**Comment by pineappleoOilPrince** [comment]
那么应该是因为你的定位权限和定位功能没有打开，你可以扫描前调用FlutterBlueElves.instance.androidCheckBlueLackWhat()来检测android端是否没有打开上述功能，如果没有就调用下面三个方法来打开对应功能
FlutterBlueElves.instance.androidApplyLocationPermission((result){})
FlutterBlueElves.instance.androidOpenLocationService((result){})
FlutterBlueElves.instance.androidApplyBluetoothPermission((result){})
具体的使用可以看我的example项目

**Comment by yh4922** [comment]
我用`permission_handler`申请了权限之后 还需要再 AndroidManifest.xml 中加上
感谢😄
