### ISSUE TITLE
The Bluetooth device has been connected, reopen the software, is there a way to connect directly without scanning?

### ISSUE THREAD

**Issue by yh4922** [pineappleoOilPrince/flutter_blue_elves#6]
已经连接过的蓝牙设备，有没有办法保存起来，下一次重新打开软件时可以直接连接 不用再次扫描

**Comment by pineappleoOilPrince** [comment]
直接连接是做不到的，且不说重新打开软件，你在安卓端光是把手机的蓝牙关闭再打开都无法再次直接连接设备，因为蓝牙重启会自动清除手机底层的蓝牙堆栈，之前的设备对象就不存在了，只能再次扫描才能将设备加入到底层蓝牙堆栈中（鸿蒙系统除外）。
而我这个插件之所以重启蓝牙还能直接连接是因为我偷偷的做了扫描操作

**Comment by pineappleoOilPrince** [comment]
你这边我建议你重新打开软件时可以去扫描设备然后再去连接目标设备，只要你体现给用户看起来是直接连接即可

**Comment by yh4922** [comment]
好的 那只能记录一下设备ID 重新扫描再连接了 感谢😀
