### ISSUE TITLE
蓝牙2.0扫描不出来

### ISSUE THREAD

**Issue by yh4922** [pineappleoOilPrince/flutter_blue_elves#8]
有一个打印机设备同时有蓝牙2.0和蓝牙4.0
蓝牙1: FP62.k +  00:15:83:FF:70:0E  【2.0】
蓝牙2: FP62.k +  C0:15:83:FF:70:0E  【4.0】
4.0的可以扫描到，2.0的扫描不到

**Comment by pineappleoOilPrince** [comment]
2.0是传统蓝牙的范畴了，本插件是针对低功耗蓝牙的，即蓝牙4.2以上

**Comment by yh4922** [comment]
好的 了解感谢
